version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp:
    depends_on:
    - mysql
    image: wpxdebug2
    ports:
    - 80:80
    restart: on-failure
    volumes:
    - ./wp:/var/www/html
     
    environment:
      VIRTUAL_HOST: content.local
      VIRTUAL_PORT: 80
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      XDEBUG_CONFIG: remote_host=host.docker.internal